// 기존 Mission 인터페이스 확장
export interface Mission {
  id: string
  title: string
  description?: string
  reward: number
  isCompleted: boolean
  completedAt?: string
  isTransferred?: boolean
  category?: string
  missionType?: string
  // 새로 추가되는 필드들
  date: string              // YYYY-MM-DD 형식, 기본값: 오늘 날짜
  templateId?: string       // 템플릿 ID, null이면 일회성 미션
}

// 미션 템플릿 인터페이스
export interface MissionTemplate {
  id: string
  title: string
  description: string
  reward: number
  category: string
  missionType: 'daily' | 'event'
  isActive: boolean
  createdAt: string
  updatedAt: string
}

// 미션 인스턴스 (날짜별 실제 미션)
export interface MissionInstance {
  id: string
  templateId: string | null  // null이면 일회성 미션
  date: string              // YYYY-MM-DD 형식
  title: string
  description: string
  reward: number
  category: string
  missionType: 'daily' | 'event'
  isCompleted: boolean
  completedAt?: string
  isTransferred?: boolean
}

// 날짜별 요약 정보
export interface DateSummary {
  date: string              // YYYY-MM-DD
  totalMissions: number
  completedMissions: number
  totalReward: number
  earnedReward: number
  lastUpdated: string
}

// 사용자 설정
export interface UserSettings {
  id: string
  autoGenerateDays: number  // 미래 며칠까지 데일리 미션 생성할지
  dataRetentionDays: number // 과거 데이터 보관 일수
  notificationEnabled: boolean
  backupEnabled: boolean
  createdAt: string
  updatedAt: string
}

// 데이터베이스 설정
export const DB_CONFIG = {
  NAME: 'KidsAllowanceDB',
  VERSION: 1,
  STORES: {
    MISSION_TEMPLATES: 'missionTemplates',
    MISSION_INSTANCES: 'missionInstances', 
    DATE_SUMMARIES: 'dateSummaries',
    USER_SETTINGS: 'userSettings'
  },
  INDEXES: {
    INSTANCES_BY_DATE: 'by_date',
    INSTANCES_BY_TEMPLATE: 'by_template',
    SUMMARIES_BY_DATE: 'by_date'
  }
}